apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dynamic-refresh-operator-reader
  namespace: dynamic-refresh-operator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
# - apiGroups: [""]
#   resources: ["configmaps"]
#   verbs: ["get", "list", "watch"]
- apiGroups: ["config.openshift.io"]
  resources: ["infrastructures"]
  verbs: ["get", "list", "watch"]