apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dynamic-refresh-operator-configmap-reader-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: dynamic-refresh-operator-sa
  namespace: dynamic-refresh-operator
roleRef:
  kind: Role
  name: dynamic-refresh-operator-configmap-reader
  apiGroup: rbac.authorization.k8s.io
