apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dynamic-refresh-operator-configmap-reader
  namespace: default
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]

