apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynamic-refresh-operator-secret-admin-binding
  namespace: dynamic-refresh-operator
subjects:
- kind: ServiceAccount
  name: dynamic-refresh-operator-sa
  namespace: dynamic-refresh-operator
roleRef:
  kind: ClusterRole
  name: dynamic-refresh-operator-secret-admin
  apiGroup: rbac.authorization.k8s.io
