#!/bin/sh

# A hackish script to build bundle and index images for given driver + operator images.
# The output is available in opm-bundle directory.

set -o errexit
set -o nounset
set -o pipefail

# if [ "$#" -ne "4" ]; then
#     echo "Usage: $0 <input_driver_image> <input_operator_image> <output_bundle_image> <output_index_image>"
#     exit 1
# fi

TOOL_BIN=$(which podman 2>/dev/null || which docker 2>/dev/null)
if [ "$? " -ne "0" ]; then
	echo "Error: No suitable container manipulation tool (podman, docker) found in \$PATH" 1>&2
	exit 1
fi

TOOL_NAME=$(basename $TOOL_BIN)
# DRIVER_IMAGE=$1
# OPERATOR_IMAGE=$2
BUNDLE_IMAGE="quay.io/ckyal/dynamic-refresh-operator:bundle"
INDEX_IMAGE="quay.io/ckyal/dynamic-refresh-operator:index"

# Prepare output dir
mkdir -p opm-bundle
pushd opm-bundle
cp -r -v ../../config/* .

MANIFEST=manifests/stable/dynamic-refresh-operator.clusterserviceversion.yaml

# Replace images in the manifest - error prone, needs to be in sync with image-references.
# sed -i $MANIFEST -e "s~quay.io/openshift/origin-gcp-filestore-csi-driver-operator:latest~$OPERATOR_IMAGE~" -e "s~quay.io/openshift/origin-gcp-filestore-csi-driver:latest~$DRIVER_IMAGE~"

# Build the bundle and push it
$TOOL_BIN build -t $BUNDLE_IMAGE -f bundle.Dockerfile .
$TOOL_BIN push $BUNDLE_IMAGE

# Build the index image and push it
opm index add --bundles $BUNDLE_IMAGE --tag $INDEX_IMAGE --container-tool $TOOL_NAME
$TOOL_BIN push $INDEX_IMAGE


echo
echo --------------------
echo "Index image created"
echo "Copy following snipped to apply it to your cluster"
echo

# Show oc apply -f - <<EOF to copy-paste into shell
cat <<REAL_EOF
oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: dynamic-refresh
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: $INDEX_IMAGE
  publisher: Chirag Kyal Dev Test Dynamic Refresh
  displayName: Chirag Kyal Dev Test Dynamic Refresh
EOF
REAL_EOF

echo

popd
