updates:
  - file: "stable/dynamic-refresh-operator.clusterserviceversion.yaml" # relative to this file
    update_list:
    # replace metadata.name value
    - search: "dynamic-refresh-operator.v{MAJOR}.{MINOR}.0"
      replace: "dynamic-refresh-operator.v{FULL_VER}"
    # replace entire version line, otherwise would replace 4.3.0 anywhere
    - search: "version: {MAJOR}.{MINOR}.0"
      replace: "version: {FULL_VER}"
    - search: 'olm.skipRange: ">=4.12.0-0 <{MAJOR}.{MINOR}.0"'
      replace: 'olm.skipRange: ">=4.12.0-0 <{FULL_VER}"'
  - file: "dynamic-refresh-operator.package.yaml"
    update_list:
    - search: "currentCSV: dynamic-refresh-operator.v{MAJOR}.{MINOR}.0"
      replace: "currentCSV: dynamic-refresh-operator.{FULL_VER}"
